### ISSUE TITLE
Impure incremental builds by allowing the intermediate products dir in the sandbox

### ISSUE THREAD

**Issue by Atemu** [danielfullmer/robotnix#191]
Pure incremental builds are quite complex to support but for the time being, perhaps one could make use of the AOSP build system's own internal build caching by allowing its directories in the sandbox.  

Obviously this isn't great and very impure but I trust the build system enough to get incremental builds at least correct (even if they might not be fully reproducible) and that's good enough for hacking.

**Comment by cassandracomar** [comment]
the way I'm solving this is to add the updater dir being served by nginx to the allowedSandboxPaths, copying the previous target_files package to the release script build dir, then calling the release script. once it's done, I copy the new release files to the updater nginx directory at nginx startup by setting it as a preStart command, from the output dir of the android release files path in /nix/store. I'll post a link to my configuration once I've got it tested.

**Comment by Atemu** [comment]
No, this an impure hack, not a proper solution. It also doesn't work because the build system relies on mtime which is always the same, regardless of whether the source changed or not.
