### ISSUE TITLE
LineageOS builds failing for certain devices

### ISSUE THREAD

**Issue by danielfullmer** [danielfullmer/robotnix#28]
I built the `build.checkAndroid` target for all `lineageos-17.1` devices. Here is a checklist with the failing devices, along with the error message I encountered.

- [ ]  a3xelte, a5xelte, a7xelte, j7elte, s5neolte
  `# mkdir: cannot create directory 'hardware/samsung/slsi': Permission denied`
- [ ]  jasmine_sprout
  `build/make/core/board_config.mk:125: error: No config file found for TARGET_DEVICE jasmine_sprout.`
- [ ]  z2_plus
  `build/make/target/product/telephony_vendor.mk:24: error: _nic.PRODUCTS.[[device/zuk/z2/plus/lineage_z2_plus.mk]]: "device/zuk/z2_plus/device.mk" does not exist.`

**Comment by Atemu** [comment]
Could the last one be due to us replacing _s with /s?

**Comment by danielfullmer** [comment]
@Atemu Good eye. That's probably what's causing the issue with `jasmine_sprout` as well.

**Comment by Atemu** [comment]
Looks like the first one needed to be `samsung_slsi`, so that got fixed too. Great work!
