### ISSUE TITLE
generate keys fails

### ISSUE THREAD

**Issue by eyecreate** [danielfullmer/robotnix#39]
When running nix-build as in the README, generating keys fails with this message:

```../../generate-keys: line 10: generate_verity_key: command not found```

Which refers to this line of script:

```generate_verity_key -convert verity.x509.pem verity_key || exit 1```

Not sure why, but it seems this program is unable to be found.

**Comment by danielfullmer** [comment]
Should be fixed in dd4246d3b1b8ac8b05397bb7e2dabfa695b132dd . I assume you are building for marlin/sailfish?

**Comment by eyecreate** [comment]
Yep I am. This looks like it fixed it. Thanks!
