### ISSUE TITLE
Support for Pixel 4a (5G) and Pixel 5

### ISSUE THREAD

**Issue by danielfullmer** [danielfullmer/robotnix#52]
The git tags for these were recently released. This is a tracking issue for what we need to do to support these phones.

- [x] Basic setup in `pixel/default.nix`, etc. (292c728662e0d8826e036b0c2f89f0b376f29616)
- [x] Fetch tags for source
- [x] Android-prepare-vendor support (https://github.com/AOSPAlliance/android-prepare-vendor/pull/47) _(Pixel 5 nearly done 2020-01-01)_
- [x] Build kernel from source (It appears to include some different sub-repos compared with previous phones)

**Comment by codethief** [comment]
Hi Daniel, I'd really be interested in getting this to work for my Pixel 5. Does this issue concern only the AOSP/vanilla build or also the GrapheneOS one?

**Comment by danielfullmer** [comment]
Redfin / bramble support should be working in robotnix since early March in 1d0b42efdc9626f8eccb4af9394e8d1800f2e67a
